"""add_day_log_table

Revision ID: a78ac56124b2
Revises: update_task_enums
Create Date: 2025-08-08 13:42:18.583316

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a78ac56124b2'
down_revision: Union[str, Sequence[str], None] = 'update_task_enums'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'deadline')
    op.alter_column('users', 'timezone',
               existing_type=postgresql.ENUM('UTC', 'EST', 'PST', 'CST', 'MST', 'IST', name='timezoneenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.String(),
               type_=postgresql.ENUM('UTC', 'EST', 'PST', 'CST', 'MST', 'IST', name='timezoneenum'),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###